In [0]:
from google.colab import files

In [2]:
uploaded=files.upload()

Saving Churn_Modelling.csv to Churn_Modelling.csv


In [0]:
import io
import pandas as pd

In [0]:
df= pd.read_csv(io.BytesIO(uploaded['Churn_Modelling.csv']))

In [5]:
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [7]:
df['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [0]:
x=df.iloc[:,3:-1]

In [9]:
x

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0             619    France  Female  ...          1               1        101348.88
1             608     Spain  Female  ...          0               1        112542.58
2             502    France  Female  ...          1               0        113931.57
3             699    France  Female  ...          0               0         93826.63
4             850     Spain  Female  ...          1               1         79084.10
...           ...       ...     ...  ...        ...             ...              ...
9995          771    France    Male  ...          1               0         96270.64
9996          516    France    Male  ...          1               1        101699.77
9997          709    France  Female  ...          0               1         42085.58
9998          772   Germany    Male  ...          1               0         92888.52
9999          792    France  Female  ...          1               0         38190.78

[10000 rows x 10 columns]

In [0]:
y=df.iloc[:,-1:]

In [11]:
y.head()
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 1 columns):
Exited    10000 non-null int64
dtypes: int64(1)
memory usage: 78.2 KB


In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder


In [0]:
from sklearn.compose import ColumnTransformer


In [0]:
ct=ColumnTransformer([('Geography', OneHotEncoder(),[1] )], remainder='passthrough')

In [0]:
x=ct.fit_transform(x)

In [16]:
x[0]

array([1.0, 0.0, 0.0, 619, 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [0]:
label=LabelEncoder()
x[:,4]=label.fit_transform(x[:,4])

In [0]:
x=x[:,1:]

In [19]:
x[0]

array([0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [20]:
x.shape

(10000, 11)

In [0]:
 from sklearn.preprocessing import StandardScaler

In [0]:
sc=StandardScaler()

In [0]:
x=sc.fit_transform(x)

In [0]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.3) 

In [25]:
x_train.shape

(7000, 11)

In [26]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [27]:
classifier=Sequential()

In [28]:
classifier.add(Dense(units=6, activation='relu', input_dim=11))
classifier.add(Dense(units=1, activation='sigmoid'))
classifier.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])





Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [29]:
classifier.fit(x_train, y_train, batch_size=10, epochs=100)




Epoch 1/100





7000/7000 [==============================] - 1s 198us/step - loss: 0.5880 - acc: 0.7181
Epoch 2/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.4603 - acc: 0.8066
Epoch 3/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.4334 - acc: 0.8150
Epoch 4/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.4170 - acc: 0.8239
Epoch 5/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.4027 - acc: 0.8299
Epoch 6/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.3901 - acc: 0.8346
Epoch 7/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3802 - acc: 0.8386
Epoch 8/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3721 - acc: 0.8426
Epoch 9/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3654 - acc: 0.8497
Epoch 10/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.3602 - acc

In [0]:
ypred=classifier.predict(x_test)

In [0]:
ypred=ypred>0.5

In [32]:
from sklearn.metrics import confusion_matrix
confusion_matrix(ypred, y_test)

array([[2316,  339],
       [  81,  264]])

In [0]:
from sklearn.metrics import accuracy_score

In [34]:
accuracy_score(ypred, y_test)


0.86